// Sprite editor
export {
  createSpriteEditorStore,
  SpriteEditorProvider,
  useSpriteDispatch,
  useSpriteSelector,
  useSpriteStore,
  type SpriteEditorStore,
  type SpriteEditorRootState,
  type SpriteEditorDispatch,
} from "./spriteEditorKit";
export {
  spriteEditorReducer,
  createInitialState,
  type SpriteEditorState,
  type Tool,
  type LayerMeta,
  setCanvasW,
  setCanvasH,
  setGridSize,
  setZoom,
  setTool,
  setToolSize,
  setColor,
  addLayer,
  deleteLayer,
  setActiveLayerId,
  renameLayer,
  toggleLayerVisibility,
  setLayerTint,
  reorderLayers,
  addFrame,
  deleteFrame,
  setCurrentFrame,
  setFrameCount,
  setPreviewFps,
  toggleOnionPrev,
  toggleOnionNext,
  toggleShowBg,
  setTransformAllFrames,
  setRotAngle,
  setTransformRect,
  resetTransformRect,
  bumpVersion,
  restoreState,
} from "./spriteEditorSlice";
export { createCanvasOps, type CanvasOps } from "./canvas-ops";

// Record editor (Item, Wearable, BaseAvatar, Critter)
export {
  createRecordEditorStore,
  RecordEditorProvider,
  useRecordDispatch,
  useRecordSelector,
  useRecordStore,
  type RecordEditorStore,
  type RecordEditorRootState,
  type RecordEditorDispatch,
} from "./recordEditorKit";
export {
  recordEditorReducer,
  createRecordEditorInitialState,
  type RecordEditorState,
  type VariantData,
  type TileData,
  setName,
  setDescription,
  addTag,
  removeTag,
  addTarget,
  removeTarget,
  addBehavior,
  removeBehavior,
  updateBehavior,
  setStateProperties,
  addVariant,
  removeVariant,
  updateVariant,
  updateVariantDimension,
  setBaseAvatarRef,
  restoreRecordState,
  addTile,
  removeTile,
  updateTile,
} from "./recordEditorSlice";

// Starter pack editor
export {
  createStarterPackEditorStore,
  StarterPackEditorProvider,
  usePackDispatch,
  usePackSelector,
  usePackStore,
  type StarterPackEditorStore,
  type StarterPackEditorRootState,
  type StarterPackEditorDispatch,
} from "./starterPackEditorKit";
export {
  starterPackEditorReducer,
  createStarterPackEditorInitialState,
  type StarterPackEditorState,
  type PackEntryData,
  type EntryCategory,
  setPackName,
  setPackDescription,
  addEntry,
  removeEntry,
  moveEntry,
  restoreStarterPackState,
} from "./starterPackEditorSlice";

// Avatar editor
export {
  createAvatarEditorStore,
  AvatarEditorProvider,
  useAvatarDispatch,
  useAvatarSelector,
  useAvatarStore,
  type AvatarEditorStore,
  type AvatarEditorRootState,
  type AvatarEditorDispatch,
} from "./avatarEditorKit";
export {
  avatarEditorReducer,
  createAvatarEditorInitialState,
  type AvatarEditorState,
  type EquippedEntryData,
  setSelectedIndex,
  setBaseAvatar,
  setBaseAvatarTints,
  setBaseAvatarTransform,
  addWearable,
  removeWearable,
  moveWearable,
  setWearableTints,
  setWearableTransform,
  setWearableState,
  restoreAvatarState,
} from "./avatarEditorSlice";

// Room editor
export {
  createRoomEditorStore,
  RoomEditorProvider,
  useRoomEditorDispatch,
  useRoomEditorSelector,
  useRoomEditorStore,
  type RoomEditorStore,
  type RoomEditorRootState,
  type RoomEditorDispatch,
} from "./roomEditorKit";
export {
  roomEditorReducer,
  createRoomEditorInitialState,
  type RoomEditorState,
  type PlacedTile,
  type RoomExitData,
  type RoomItemData,
  type ChannelTintData,
  type RoomCritterData,
  type TileAttributeData,
  type BackgroundDataState,
  setRoomName,
  setGridWidth,
  setGridHeight,
  addPlacedTile,
  setPlacedTiles,
  addExit,
  updateExit,
  removeExit,
  setSpawnTiles,
  setBlockingEdges,
  setBackground,
  addRoomItem,
  removeRoomItem,
  setRoomItems,
  updateRoomItemState,
  updateRoomItemTints,
  addRoomCritter,
  removeRoomCritter,
  setRoomCritters,
  updateCritterArea,
  updateCritterName,
  updateCritterState,
  setTileAttributes,
  addRoomBehavior,
  removeRoomBehavior,
  updateRoomBehavior,
  restoreRoomState,
} from "./roomEditorSlice";
