/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as HandleIndexRouteImport } from './routes/$handle/index'
import { Route as HandleNsidIndexRouteImport } from './routes/$handle/$nsid/index'
import { Route as HandleNsidTidRouteImport } from './routes/$handle/$nsid/$tid'
import { Route as CreateActorNsidTidRouteImport } from './routes/create/$actor/$nsid/$tid'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const HandleIndexRoute = HandleIndexRouteImport.update({
  id: '/$handle/',
  path: '/$handle/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleNsidIndexRoute = HandleNsidIndexRouteImport.update({
  id: '/$handle/$nsid/',
  path: '/$handle/$nsid/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleNsidTidRoute = HandleNsidTidRouteImport.update({
  id: '/$handle/$nsid/$tid',
  path: '/$handle/$nsid/$tid',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateActorNsidTidRoute = CreateActorNsidTidRouteImport.update({
  id: '/$actor/$nsid/$tid',
  path: '/$actor/$nsid/$tid',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$handle/': typeof HandleIndexRoute
  '/create/': typeof CreateIndexRoute
  '/$handle/$nsid/$tid': typeof HandleNsidTidRoute
  '/$handle/$nsid/': typeof HandleNsidIndexRoute
  '/create/$actor/$nsid/$tid': typeof CreateActorNsidTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$handle': typeof HandleIndexRoute
  '/create': typeof CreateIndexRoute
  '/$handle/$nsid/$tid': typeof HandleNsidTidRoute
  '/$handle/$nsid': typeof HandleNsidIndexRoute
  '/create/$actor/$nsid/$tid': typeof CreateActorNsidTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/$handle/': typeof HandleIndexRoute
  '/create/': typeof CreateIndexRoute
  '/$handle/$nsid/$tid': typeof HandleNsidTidRoute
  '/$handle/$nsid/': typeof HandleNsidIndexRoute
  '/create/$actor/$nsid/$tid': typeof CreateActorNsidTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/inventory'
    | '/login'
    | '/settings'
    | '/$handle/'
    | '/create/'
    | '/$handle/$nsid/$tid'
    | '/$handle/$nsid/'
    | '/create/$actor/$nsid/$tid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/login'
    | '/settings'
    | '/$handle'
    | '/create'
    | '/$handle/$nsid/$tid'
    | '/$handle/$nsid'
    | '/create/$actor/$nsid/$tid'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/inventory'
    | '/login'
    | '/settings'
    | '/$handle/'
    | '/create/'
    | '/$handle/$nsid/$tid'
    | '/$handle/$nsid/'
    | '/create/$actor/$nsid/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  HandleIndexRoute: typeof HandleIndexRoute
  HandleNsidTidRoute: typeof HandleNsidTidRoute
  HandleNsidIndexRoute: typeof HandleNsidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/$handle/': {
      id: '/$handle/'
      path: '/$handle'
      fullPath: '/$handle/'
      preLoaderRoute: typeof HandleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/$nsid/': {
      id: '/$handle/$nsid/'
      path: '/$handle/$nsid'
      fullPath: '/$handle/$nsid/'
      preLoaderRoute: typeof HandleNsidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/$nsid/$tid': {
      id: '/$handle/$nsid/$tid'
      path: '/$handle/$nsid/$tid'
      fullPath: '/$handle/$nsid/$tid'
      preLoaderRoute: typeof HandleNsidTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$actor/$nsid/$tid': {
      id: '/create/$actor/$nsid/$tid'
      path: '/$actor/$nsid/$tid'
      fullPath: '/create/$actor/$nsid/$tid'
      preLoaderRoute: typeof CreateActorNsidTidRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateIndexRoute: typeof CreateIndexRoute
  CreateActorNsidTidRoute: typeof CreateActorNsidTidRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateIndexRoute: CreateIndexRoute,
  CreateActorNsidTidRoute: CreateActorNsidTidRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  HandleIndexRoute: HandleIndexRoute,
  HandleNsidTidRoute: HandleNsidTidRoute,
  HandleNsidIndexRoute: HandleNsidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
